### ISSUE TITLE
QA ONLY: Form errors should be showing on password/reset/confirm/ 

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/pimp-my-cause-django#77]
Form errors should be showing on password/reset/confirm/ when users are typing different password - currently it just reloads the page and blanks out the password fields.

**Comment by mangogeek** [comment]
Issues noted when registering an account (we paired and registered one marketer and one cause):

1) Twitter (optional) field - needs URL,  this is not obvious when filling in the form. Is there a way to only require the Twitter handle?
2) When you create an account and click 'register', the registration page appears again with two extra blank fields.  These need a label to identify they are for passwords. The password field should appear at the first registration page?
3) On registration, if the penultimate box agreeing to terms and conditions is not ticked, when click registration the form clears of all information. To change this, keep the form's information and put a red comment saying the box should be ticked.
4) Signed up (either as marketer or cause) and checked box for newsletter signup, an option to sign up for newsletter appears after registration asking to signup again. Change this to be dependent on whether user signed up already or not?
5) After completing registration successfully it still asks sign-up instead of showing as signed up already.

When you want to sign in:
1) Email address`s default value is post code
2) In the error message `both fields may be case sensitive` written. email address should not be case sensitive.

Others:
1) Profile form - country field needs caption
